- name: Install system packages
  hosts: all
  become: yes

  tags:
    - install

  tasks:
    - name: install python system pkgs
      apt: name="{{ item }}" update_cache=yes cache_valid_time=3600
      with_items:
        - python-dev
        - python-virtualenv
        - python-setuptools
        - python-pip
